In [1]:
import torch

In [2]:
#create a matric
matrix1 = torch.tensor([[1,1],[2,2]])
matrix1.shape

torch.Size([2, 2])

In [3]:
matrix1.ndim

2

In [ ]:
tensor2 = torch.tensor([[[1,1], [2,2]], [[3,3], [4,4]]])
tensor2

tensor([[[1, 1],
         [2, 2]],

        [[3, 3],
         [4, 4]]])

In [ ]:
tensor2.shape

torch.Size([2, 2, 2])

In [ ]:
tensor2.ndim

3

In [23]:
#create a matrix with zeros
zero_matrix = torch.zeros(3,3)
zero_matrix

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
#creating 3-dim zeros tensor
zero_tensor = torch.zeros(3,3,2)

In [25]:
zero_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [26]:
#tesors with ones
ones_tensor = torch.ones(2,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones_tensor2 = torch.ones(size=(2,4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
#creating tensor with random values
torch.rand(2)

tensor([0.7072, 0.0694])

In [13]:
torch.rand(3,2)

tensor([[0.8358, 0.2238],
        [0.1874, 0.9463],
        [0.2654, 0.2444]])

In [16]:
torch.rand(2,3,4)

tensor([[[0.0392, 0.4236, 0.2136, 0.3034],
         [0.8107, 0.1388, 0.1512, 0.6883],
         [0.5323, 0.0436, 0.0999, 0.7273]],

        [[0.9553, 0.8282, 0.7301, 0.4865],
         [0.4598, 0.0636, 0.5253, 0.4175],
         [0.3443, 0.0779, 0.3437, 0.5464]]])

In [17]:
torch.rand(2,3,4,1)

tensor([[[[0.9558],
          [0.9636],
          [0.0883],
          [0.2843]],

         [[0.3541],
          [0.3085],
          [0.3098],
          [0.7690]],

         [[0.8648],
          [0.4339],
          [0.3519],
          [0.5047]]],


        [[[0.5214],
          [0.5040],
          [0.8297],
          [0.9501]],

         [[0.2469],
          [0.9165],
          [0.1570],
          [0.8530]],

         [[0.2017],
          [0.9145],
          [0.2813],
          [0.1548]]]])

In [18]:
#example creating a random tensor for image
img_tensor = torch.rand(3,255,255)  #torch.rand('color_channel', 'hight', 'width')

In [19]:
img_tensor

tensor([[[0.9103, 0.7489, 0.5521,  ..., 0.4081, 0.5688, 0.3716],
         [0.6832, 0.6409, 0.0721,  ..., 0.4119, 0.4797, 0.2860],
         [0.0166, 0.5867, 0.0762,  ..., 0.3418, 0.3680, 0.7385],
         ...,
         [0.9453, 0.4747, 0.6930,  ..., 0.4665, 0.9363, 0.9160],
         [0.3134, 0.5524, 0.8703,  ..., 0.3834, 0.4642, 0.4517],
         [0.7167, 0.8286, 0.0080,  ..., 0.3016, 0.2646, 0.1729]],

        [[0.2477, 0.2197, 0.7881,  ..., 0.7816, 0.7911, 0.3500],
         [0.2867, 0.9131, 0.4609,  ..., 0.6927, 0.3741, 0.5689],
         [0.9245, 0.5241, 0.9193,  ..., 0.3352, 0.2604, 0.9776],
         ...,
         [0.1883, 0.9948, 0.5039,  ..., 0.2901, 0.1020, 0.7595],
         [0.2075, 0.7966, 0.2319,  ..., 0.7759, 0.6425, 0.5771],
         [0.5170, 0.4214, 0.2681,  ..., 0.2027, 0.2610, 0.7203]],

        [[0.1889, 0.0151, 0.2743,  ..., 0.6778, 0.0636, 0.0600],
         [0.6618, 0.8785, 0.0520,  ..., 0.6380, 0.7586, 0.9158],
         [0.4356, 0.2593, 0.3330,  ..., 0.1534, 0.3899, 0.

In [20]:
img_tensor.ndim

3

In [21]:
img_tensor.shape

torch.Size([3, 255, 255])

In [30]:
# tensors with range of values
range_tensor = torch.arange(10)
range_tensor


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
range_tensor2 = torch.arange(start = 5, end = 15)
range_tensor2

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
#create a tensor of a shape like other tensor
zero_tensor_with_like = torch.zeros_like(range_tensor)
zero_tensor_with_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
ones_tensor_with_like = torch.ones_like(range_tensor)
ones_tensor_with_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
#tensor datatypes

tensor_float32 = torch.tensor([1.0,2.0,3.0])
tensor_float32

tensor([1., 2., 3.])

In [5]:
tensor_float32.dtype

torch.float32

In [10]:
tensor_float64 = torch.tensor([3,4,5], dtype = torch.float64)
tensor_float64.dtype

torch.float64

In [11]:
tensor_int = torch.tensor([1,2,3],
                          dtype=int, #determine the dtype
                          device = None, #select the device type
                          requires_grad=False # if required to calculate the gradient
                          )

In [13]:
# change dtype of existing tensors
tensor_float16 = tensor_int.type(torch.float16)
tensor_float16.dtype

torch.float16

In [14]:
#things to be careful while doing tensor computation
# 1. Tensor should be in the correct dtype
# 2. Tensor not having right shape
# 3. Tensor not being in right device

In [15]:
# Matrix multipilicaiton rules
# 1. Inner dimension of the two given tensor should be equal
# eg. (a,b)* (b, c)  where a,b,c are the dimensions of the matrix
# here 'b' is column of first tensor and 'b' in the second is the row, both should be same
# 2. The output size of the tensor will be of size of outer dimension i.e a*b size


In [17]:
tensor2by3 = torch.rand(2,3)
tensor3by4 = torch.rand(3,4)

In [ ]:
#multuplying those tensor gives output of 2*4 matrix
tensor2by3 @ tensor3by4

tensor([[0.5061, 0.4659, 0.5741, 0.4345],
        [0.5000, 0.7451, 0.6796, 0.6470]])

In [19]:
torch.matmul(tensor2by3 , tensor3by4)

tensor([[0.5061, 0.4659, 0.5741, 0.4345],
        [0.5000, 0.7451, 0.6796, 0.6470]])

In [20]:
# elementwise matrix multipllication
(tensor2by3 @ tensor3by4) * (tensor2by3 @ tensor3by4)

tensor([[0.2561, 0.2171, 0.3295, 0.1888],
        [0.2500, 0.5551, 0.4619, 0.4186]])

In [ ]:
#matrix transpose
(tensor2by3 @ tensor3by4) @ (torch.transpose(tensor2by3 @ tensor3by4, dim0=1, dim1=0))

tensor([[0.9915, 1.2714],
        [1.2714, 1.6855]])