In [1]:
import torch 

In [23]:
#while initialy creating a tensor, requires_grad functionalaity is 'False' by default
randomTensor= torch.randn(3)
randomTensor.requires_grad

False

In [24]:
randomTensor2 = torch.randn(5, requires_grad= True)
randomTensor2.requires_grad

#When ever we perform any operations with this 'randomTensor2' tensor, pytorch creates computational graph under the hood.

True

In [25]:
myOutput = randomTensor2+5
# for above operation the compuitation graph looks like having 2 input nodes i.e. randomTensor2 and 5 and where output node in my output and operation in the middle of the both nodes in sum

In [26]:
print(myOutput)

tensor([5.0689, 4.0397, 3.6003, 3.7063, 4.7166], grad_fn=<AddBackward0>)


In [27]:
newOutput = myOutput*myOutput*7

In [28]:
print(newOutput)

tensor([179.8566, 114.2333,  90.7330,  96.1558, 155.7237],
       grad_fn=<MulBackward0>)


In [29]:
newOutput = newOutput.mean()

In [30]:
#now this backward() function calculates the derrivative of function newOutput with respect to randomTensor2
newOutput.backward()# d(newOutput)/d randomTensor2
print(randomTensor2.grad)

tensor([14.1929, 11.3111, 10.0807, 10.3776, 13.2065])


In [32]:
#sometime we need to stop the tracking the gradient so we have following options:
#1. var.requires._grad_(false)
#2. var.detach()
#3. with torch.no_grad()
randomTensor2.requires_grad_(False)
#or
randomTensor2.detach()
#or
with torch.no_grad():
    output2 = randomTensor2+5
    
print(randomTensor2)

tensor([ 0.0689, -0.9603, -1.3997, -1.2937, -0.2834])


In [37]:
#new Example
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    print(f'Iteration', epoch, f':',  model_output)

    model_output.backward()
    print(f'Iteration', epoch, f':', weights.grad)

Iteration 0 : tensor(12., grad_fn=<SumBackward0>)
Iteration 0 : tensor([3., 3., 3., 3.])
Iteration 1 : tensor(12., grad_fn=<SumBackward0>)
Iteration 1 : tensor([6., 6., 6., 6.])
Iteration 2 : tensor(12., grad_fn=<SumBackward0>)
Iteration 2 : tensor([9., 9., 9., 9.])


In [39]:
#Example for reseting the gradient 
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    print(f'Iteration', epoch, f':',  model_output)

    model_output.backward()
    print(f'Iteration', epoch, f':', weights.grad)
    
    #function to reset the gradient
    weights.grad.zero_()

Iteration 0 : tensor(12., grad_fn=<SumBackward0>)
Iteration 0 : tensor([3., 3., 3., 3.])
Iteration 1 : tensor(12., grad_fn=<SumBackward0>)
Iteration 1 : tensor([3., 3., 3., 3.])
Iteration 2 : tensor(12., grad_fn=<SumBackward0>)
Iteration 2 : tensor([3., 3., 3., 3.])


In [46]:
# Example of forward and backwardpass
input1= torch.tensor(1.0)
output1 = torch.tensor(2.0)

weight1= torch.tensor(1.0, requires_grad=True)

output1_hat = weight1*input1
loss = (output1_hat-output1) ** 2
print(loss)
loss.backward()
print(weight1.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
