In [66]:
#required packages
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd

In [42]:
# data = pd.read_csv('./datasets/weather.csv', header=None)
# data = data.to_numpy()
# X = data[1:, 1:-1].astype(float)
# y = data[1:,-1 ].astype(float)
# data.head()

In [43]:
#creating dataset class
class WeatherDataset(Dataset):

    # Loading dataset from local system
    def __init__(self):
        data = pd.read_csv('./datasets/weather.csv', header=None)
        data = data.to_numpy()
        X = data[1:, 1:-1].astype(float)
        self.X = torch.from_numpy(X)

        y = data[1:,-1 ].astype(float)      
        self.y = torch.from_numpy(y)  

    def __getitem__(self, index):
        return self.X[index], self.y[index]
    
    def __len__(self):
        return self.X.shape[0]

In [44]:
weather_dataset = WeatherDataset()

In [45]:
#viewing first data
first_data = weather_dataset.__getitem__(1)

In [46]:
#viewing first data using another way
first_data_1 = weather_dataset[1]

In [47]:
#printing features and labels saperately
features, label = first_data
print(features, label)

tensor([52., 39.,  0.], dtype=torch.float64) tensor(52., dtype=torch.float64)


In [48]:
#dataloader concept
dataloader = DataLoader(dataset =weather_dataset,batch_size=4, shuffle=True )

In [49]:
dataloader

In [67]:
#viewing the how the data is interpreted by dataloader
iter_dataloader = iter(dataloader)
data = next(iter_dataloader)
data

[tensor([[7.1000e+01, 5.2000e+01, 0.0000e+00],
         [9.2000e+01, 6.8000e+01, 4.0000e-02],
         [6.5000e+01, 4.2000e+01, 0.0000e+00],
         [6.7000e+01, 5.4000e+01, 0.0000e+00]], dtype=torch.float64),
 tensor([69., 88., 67., 67.], dtype=torch.float64)]

In [68]:
features, labels = data
print(features)
print(labels)

tensor([[7.1000e+01, 5.2000e+01, 0.0000e+00],
        [9.2000e+01, 6.8000e+01, 4.0000e-02],
        [6.5000e+01, 4.2000e+01, 0.0000e+00],
        [6.7000e+01, 5.4000e+01, 0.0000e+00]], dtype=torch.float64)
tensor([69., 88., 67., 67.], dtype=torch.float64)


In [69]:
#preparing hyperparamaters for sample training loop
total_samples = weather_dataset.__len__()
import math
n_iterations = math.ceil(total_samples/4)
epochs = 5
print(total_samples, n_iterations)

13509 3378


In [70]:
#sample training loop
for epoch in range(epochs):
    for i , (inputs, labels) in enumerate(dataloader):
        if(i+1)%10 == 0:
            print(f'Epoch Count = {epoch+1}/ {epochs} || Step ={i+1}/{n_iterations} || Inputs = {inputs.shape}')


Epoch Count = 1/ 5 || Step =10/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =20/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =30/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =40/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =50/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =60/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =70/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =80/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =90/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =100/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =110/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =120/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =130/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =140/3378 || Inputs = torch.Size([4, 3])
Epoch Count = 1/ 5 || Step =150/3378 || Inputs = torch.Si