In [11]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd

In [12]:
# data = pd.read_csv('./datasets/weather.csv', header=None)
# data = data.to_numpy()
# X = data[1:, 1:-1].astype(float)
# y = data[1:,-1 ].astype(float)
# data.head()

In [15]:
class WeatherDataset(Dataset):

    # Loading dataset from local system
    def __init__(self):
        data = pd.read_csv('./datasets/weather.csv', header=None)
        data = data.to_numpy()
        X = data[1:, 1:-1].astype(float)
        self.X = torch.from_numpy(X)

        y = data[1:,-1 ].astype(float)      
        self.y = torch.from_numpy(y)  

    def __getitem__(self, index):
        return self.X[index], self.y[index]
    
    def __len__(self):
        return self.X.shape[0]

In [16]:
weather_dataset = WeatherDataset()

In [17]:
first_data = weather_dataset.__getitem__(1)

In [18]:
first_data_1 = weather_dataset[1]

In [19]:
features, label = first_data
print(features, label)

tensor([52., 39.,  0.], dtype=torch.float64) tensor(52., dtype=torch.float64)


In [35]:
#dataloader concept
dataloader = DataLoader(dataset =weather_dataset,batch_size=4, shuffle=True )

In [36]:
dataloader

In [37]:
iter_dataloader = iter(dataloader)
data = next(iter_dataloader)
data

[tensor([[57., 42.,  0.],
         [69., 57.,  0.],
         [64., 52.,  0.],
         [75., 60.,  0.]], dtype=torch.float64),
 tensor([57., 67., 64., 85.], dtype=torch.float64)]

In [39]:
features, labels = data
print(features)
print(labels)

tensor([[57., 42.,  0.],
        [69., 57.,  0.],
        [64., 52.,  0.],
        [75., 60.,  0.]], dtype=torch.float64)
tensor([57., 67., 64., 85.], dtype=torch.float64)
