In [1]:
import torch

In [2]:
myTensor = torch.tensor([1.0,2.0,3.0])

In [3]:
myTensor

tensor([1., 2., 3.])

In [5]:
#Check if cuda support is available in current system
torch.cuda.is_available()

False

In [8]:
#creating scalar empty tensor
scalarTensor = torch.empty(1)
print(scalarTensor)

tensor([-1.8891e+26])


In [9]:
#creating a 2d empty tensor
tensor2d= torch.empty(2,3)
print(tensor2d)

tensor([[9.2508e-41, 2.1398e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [10]:
#creating a 3d empty tensor
tensor3d = torch.empty(2,3,4)
print(tensor3d)

tensor([[[9.2777e-41, 2.1398e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [11]:
#creating a tensor with random values
randomTensor = torch.rand(3,5)
print(randomTensor)

tensor([[0.8356, 0.7063, 0.0421, 0.3254, 0.4151],
        [0.9230, 0.7328, 0.4480, 0.4100, 0.6827],
        [0.4785, 0.6703, 0.0290, 0.8826, 0.7689]])


In [12]:
#creating a tensor with zeros and ones
zerosTensor = torch.zeros(3,3)
print(zerosTensor)
onesTensor = torch.ones(4,4)
print(onesTensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [13]:
#basic operations with tensors
val1 = torch.rand(3,3)
val2 = torch.rand(3,3)

val1.add(val2)

tensor([[0.7009, 0.5573, 0.7848],
        [1.4929, 0.8534, 1.0380],
        [1.1360, 1.0180, 0.3505]])

In [16]:
val1.sub(val2)

tensor([[-0.2714, -0.1927, -0.4838],
        [-0.1534, -0.7672, -0.6300],
        [-0.6370,  0.8158, -0.2486]])

In [17]:
val1-val2

tensor([[-0.2714, -0.1927, -0.4838],
        [-0.1534, -0.7672, -0.6300],
        [-0.6370,  0.8158, -0.2486]])

In [18]:
torch.mul(val1, val2)

tensor([[0.1044, 0.0684, 0.0954],
        [0.5513, 0.0349, 0.1702],
        [0.2212, 0.0927, 0.0153]])

In [19]:
val1*val2

tensor([[0.1044, 0.0684, 0.0954],
        [0.5513, 0.0349, 0.1702],
        [0.2212, 0.0927, 0.0153]])

In [20]:
torch.div(val1, val2)

tensor([[0.4418, 0.4861, 0.2372],
        [0.8136, 0.0532, 0.2446],
        [0.2815, 9.0696, 0.1700]])

In [21]:
#slicing operations in tensors
tensor2 = torch.rand(5,7)
print(tensor2)
#Print all row of second column
print(tensor2[:, 1])

tensor([[0.6706, 0.7286, 0.6156, 0.1988, 0.9487, 0.8028, 0.9879],
        [0.4960, 0.1304, 0.0419, 0.5005, 0.1198, 0.5005, 0.0364],
        [0.4523, 0.6614, 0.9220, 0.9598, 0.0510, 0.5741, 0.2071],
        [0.2189, 0.7640, 0.2709, 0.1709, 0.1962, 0.7482, 0.0433],
        [0.7169, 0.8248, 0.8087, 0.6162, 0.1364, 0.6563, 0.7211]])
tensor([0.7286, 0.1304, 0.6614, 0.7640, 0.8248])


In [24]:
#print first row and all columns
print(tensor2[0, :])

tensor([0.6706, 0.7286, 0.6156, 0.1988, 0.9487, 0.8028, 0.9879])


In [26]:
#prints third row's forth item.
print(tensor2[2,3])

tensor(0.9598)


In [29]:
#prints items from last row and last column
print(tensor2[-1,-1])

tensor(0.7211)


In [35]:
tensor3 = torch.rand(4,4)
print(tensor3)
print(f'Tensor size is :', tensor3.size())

print(f'Reshaped tensor to 1* 16 : ', tensor3.view(16))

print(f'Reshaed tensor to 2*8 :' , tensor3.view(2,8))

tensor([[0.9474, 0.2521, 0.3957, 0.4241],
        [0.0095, 0.9092, 0.8409, 0.0462],
        [0.5999, 0.6158, 0.9658, 0.4753],
        [0.1904, 0.1237, 0.9529, 0.4015]])
Tensor size is : torch.Size([4, 4])
Reshaped tensor to 1* 16 :  tensor([0.9474, 0.2521, 0.3957, 0.4241, 0.0095, 0.9092, 0.8409, 0.0462, 0.5999,
        0.6158, 0.9658, 0.4753, 0.1904, 0.1237, 0.9529, 0.4015])
Reshaed tensor to 2*8 : tensor([[0.9474, 0.2521, 0.3957, 0.4241, 0.0095, 0.9092, 0.8409, 0.0462],
        [0.5999, 0.6158, 0.9658, 0.4753, 0.1904, 0.1237, 0.9529, 0.4015]])


In [44]:
#Converting numpy array to torch tensor
import numpy as np

tensor4 = torch.ones(5)
print(type(tensor4))
npArray = tensor4.numpy()
print(f'Type after conversion: ', type(npArray))

# if the tensor are stored in the share the same location, hence modifying one tensor effects the older one.
#Example
print(tensor4.add_(1))
print(npArray)


#np array to torch tensor
npArray1 = np.ones(5)
tensor5 = torch.from_numpy(npArray1)
print(tensor5)

<class 'torch.Tensor'>
Type after conversion:  <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
